interface IUser {
  filler: String;
  empNumber: String;
  firstName: String;
  lastName: String;
  middleName: String;
  preferredName: String;
  busPhone: String;
  companyCode: String;
  costCtr: String;
  costCtrDesc: String;
  filler2: String;
  status: String;
  empType: String;
  filler3: String;
  shift: String;
  email: String;
  email2: String;
  supervisorFirstName: String;
  supervisorLastName: String;
  supervisorEmail: String;
  supervisorPhone: String;
  employeeMailStop: String;
  dateOfOriginalHire: String;
  dateOfLastHire: String;
  filler4: String;
  dateOfLastPrefRev: String;
  dateOfNextPrefRev: String;
  jobCode: String;
  jobDescription: String;
  filler5: String;
  busPartnerName: String;
  filler6: String;
  busPartnerEmail: String;
  supervisorEmpNumber: String;
  companyCode2: String;
  functionDescription: String;
  location: String;
  orgChartElig: String;
  isRegistered: Boolean;
  password: String;
};

export default IUser;
